In [3]:
import numpy as np
import matplotlib.pyplot as plt

costMatrix = np.array([[0, 4, -1, -1, -1, -1, 6, -1], 
                [4, 0, 3, -1, -1, -1, -1, 5],
                [-1, 3, 0, 6, -1, -1, -1, -1],
                [-1, -1, 6, 0, 2, -1, -1, 5],
                [-1,-1,-1,2,0,3,-1,4],
                [-1,-1,-1,-1,3,0,4,-1],
                [6,-1,-1,-1,-1,4,0,2], 
                [-1,3,-1,5,4,-1,2,0]])
print(costMatrix)

[[ 0  4 -1 -1 -1 -1  6 -1]
 [ 4  0  3 -1 -1 -1 -1  3]
 [-1  3  0  6 -1 -1 -1 -1]
 [-1 -1  6  0  2 -1 -1  5]
 [-1 -1 -1  2  0  3 -1  4]
 [-1 -1 -1 -1  3  0  4 -1]
 [ 6 -1 -1 -1 -1  4  0  2]
 [-1  3 -1  5  4 -1  2  0]]


In [9]:
def ValueIter(Vfunc, costMatrix, xf):
    n = costMatrix.shape[0]  #number of state 
    costComp =-1*np.ones(n)
    Vnext = -1*np.ones(n)
    mustar = -1*np.ones(n)
    for xi in range(n):
        if xi==xf:
            Vnext[xi] = Vfunc[xi]
            mustar[xi] = xi
        else:
            for ui in range(n):
                xnext = ui
                if costMatrix[xi,ui]==-1:
                    costComp[ui] = 10**7
                else:
                    costComp[ui] = costMatrix[xi,ui] + Vfunc[xnext]
            Vnext[xi] = np.amin(costComp)
            mustar[xi] = np.argmin(costComp)
    return Vnext, mustar

In [13]:
## test our algorithm 

# find the optimal path to a4

n = 8
N = 4
xf = 3
#define terminal cost 

g = 10**7*np.ones(n)
g[xf] = 0

V = np.zeros((N,n))
mustar = np.zeros((N,n))
V[0,:] = g
for j in range(N-1):
    V[j+1,:],mustar[j+1,:] = ValueIter(V[j,:],costMatrix,xf)


In [14]:
print(mustar)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 3. 3. 3. 0. 1. 3.]
 [0. 7. 2. 3. 3. 4. 7. 3.]
 [1. 1. 2. 3. 3. 4. 6. 3.]]


In [18]:
# test 
x = -1*np.ones(N)   #state trajectory / optimal path initialization
x[0] = 0

for k in range(N-1):
    x[k+1] = mustar[N-1-k,x[k].astype(int)]

print(x)

[0. 1. 7. 3.]
